services:
  db:
    build: ./db  # Build the image using the Dockerfile in the db directory
    container_name: my-pgdb
    environment:
      - POSTGRES_DB=next-prisma
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
    networks:
      - my-network
    restart: unless-stopped

  backend:
    build: ./next-app
    container_name: my-next-prisma
    ports:
      - "3000:3000"
    volumes:
      - ./next-app:/app
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@my-pgdb:5432/next-prisma?schema=public
      - NODE_ENV=development
    depends_on:
      - db
    networks:
      - my-network

volumes:
  pgdata:

networks:
  my-network:
    name: my-network